on: [push, pull_request]
name: Test
env:
  GOPROXY: https://proxy.golang.org,direct
jobs:
  test:
    env:
      UPSTASHDIS_TEST_REDIS_ADDR: localhost:6379

    strategy:
      matrix:
        go-version: [1.18.x]
        redis-version: [6]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: go test ./... -v -cover

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
